server:
  port : 8081

supplier:
  page:
    default:
      number: 1
      size: 1000000
      sort: id, desc

spring:
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  jackson:
    serialization:
      write_dates_as_timestamps: false
      fail_on_empty_beans: false
  output:
    ansi:
      enabled: ALWAYS
  profiles:
    default: dev
  config:
    group:
      default:
        - "dev"
      production:
        - "production"
      test-h2:
        - "test-h2"
  sql:
    init:
      mode: always

  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/t1-supplier
    username: postgres
    password: postgres

---
spring:
  config:
    activate:
      on-profile: production
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://${POSTGRES_SERVER}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
---
spring:
  liquibase:
    enabled: false
  config:
    activate:
      on-profile: test-h2
    name: test
  sql:
    init:
      mode: embedded
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL;NON_KEYWORDS=USER
    username: sa
    password: sa
  h2:
    console:
      enabled: true

